config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  resources :procedures, only: [:new, :create, :show], param: :uuid

  root 'procedures#new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
	belongs_to :remedy
	has_many :tasks

	validates :activity, :number, :unit, presence: true
	validates :timeline, inclusion: { in: [ "before", "after" ]}
end

app/models/ailment.rb
class Ailment < ApplicationRecord
  validates :code, :description, presence: true, uniqueness: true

  def option_display
    ["#{code} - #{description}", id]
  end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :ailment
  belongs_to :procedure
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :physicians

  validates :name, :address, :city, :state, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :medical_record_number, :email, presence: true, uniqueness: true
  validates :first_name, :last_name, :address, :city, :state, :phone, presence: true

  has_many :procedures

  def option_display
    [
      "#{medical_record_number} - #{first_name} #{last_name}",
      id,
      {
        'data-address'  => address,
        'data-city'     => city,
        'data-state'    => state,
        'data-email'    => email,
        'data-phone'    => phone
      }
    ]
  end
end

app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :hospital
  has_many :procedures
  validates :first_name, :last_name, presence: true

  def option_display
    ["#{first_name} #{last_name}", id]
  end
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  belongs_to :remedy
  has_one :diagnosis
  has_one :ailment, through: :diagnosis
  has_many :tasks

  before_validation :set_uuid, on: :create
  after_create :create_tasks
  after_create :send_email

  def to_param
    uuid
  end

  private

  def set_uuid
    self.uuid = SecureRandom.uuid unless uuid.present?
  end

  def create_tasks
    remedy.actions.each do |action|
      operation = if action.timeline == "before"
                    :-
                  elsif action.timeline == "after"
                    :+
                  end
      time      = action.number.send(action.unit)
      action.tasks.create(
        procedure:  self,
        due_at:     self.start_at.send(operation, time)
      )
    end
  end

  def send_email
    PatientMailer.with(
      patient:    self.patient,
      procedure:  self
    ).schedule_email.deliver_now
  end
end

app/models/remedy.rb
class Remedy < ApplicationRecord
  validates :code, :description, presence: true, uniqueness: true
  has_many :actions
  has_many :diagnoses
  has_many :ailments, through: :diagnoses

  def option_display
    ["#{code} - #{description}", id]
  end
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :action
	belongs_to :procedure

  scope :before, -> { joins(:procedure).where("tasks.due_at::date < procedures.start_at::date") }
  scope :day_of, -> { joins(:procedure).where("tasks.due_at::date = procedures.start_at::date") }
  scope :after, -> { joins(:procedure).where("tasks.due_at::date > procedures.start_at::date") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end


end
  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :address, :city, :state, :phone_number)
    end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

  def create
    @procedure = Procedure.new(procedure_params.except(:ailment_id))
    @diagnosis = @procedure.build_diagnosis(ailment_id: procedure_params[:ailment_id])
  	if @procedure.save && @diagnosis.save
  		redirect_to @procedure
  	else
  		render :new
  	end
  end

  def new
    @patients   = Patient.all
    @ailments   = Ailment.all
    @remedies   = Remedy.all
    @physicians = Physician.all
  end

  def show
    @procedure    = Procedure.find_by!(uuid: params[:uuid])
    @before_tasks = @procedure.tasks.before
    @after_tasks  = @procedure.tasks.after
    @day_of_tasks = @procedure.tasks.day_of
  end

	private

	def procedure_params
		params.require(:procedure)
      .permit(:patient_id, :ailment_id, :physician_id, :remedy_id, :start_at)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.address %></td>
        <td><%= hospital.city %></td>
        <td><%= hospital.state %></td>
        <td><%= hospital.phone_number %></td>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hospital.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @hospital.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @hospital.state %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @hospital.phone_number %>
</p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuideThePatient</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Vollkorn+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fanwood+Text" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Linden+Hill" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar navbar-light bg-info justify-content-between">
      <a class="navbar-brand" href="#"> Guide the Patient </a>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </nav>
   <!-- <div class="container"> -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
    <%= yield %>


    </body>

</html>

app/views/procedures/create.html.erb
<h1>Procedures#create</h1>
<p>Find me in app/views/procedures/create.html.erb</p>

app/views/procedures/new.html.erb
<body class="schedule">
<h1 id="schedule">Surgery Scheduling</h1>

<%= form_with(url: procedures_url, local: true) do %>

<div class="container">
  <div class="row">
    <div class="form-group col-md">
      <div class="sch">
      <%= label_tag("procedure[patient_id]", "Patient") %>
    </div>
      <%= select_tag(
          "procedure[patient_id]",
          options_for_select(
            @patients.map(&:option_display).prepend(["Select", nil])
          ),
          class: "chosen-select form-control"
      )%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <div class="sch">
      <%= label_tag("patient[address]", "Address") %>
    </div>
      <%= text_field_tag(
          "patient[address]",
          nil,
          disabled: true,
          class: "form-control")
      %>
    </div>
    <div class="form-group col-md-4">
      <div class="sch">
      <%= label_tag("patient[city]", "City") %>
    </div>
      <%= text_field_tag(
          "patient[city]",
          nil,
          disabled: true,
          class: "form-control")
      %>
    </div>
    <div class="form-group col-md-2">
      <div class="sch">
      <%= label_tag("patient[state]", "State") %>
    </div>
      <%= text_field_tag(
          "patient[state]",
          nil,
          disabled: true,
          class: "form-control")
      %>
    </div>
    <div class="form-group col-md-6">
      <div class="sch">
      <%= label_tag("patient[phone]", "Phone") %>
    </div>
      <%= text_field_tag(
          "patient[phone]",
          nil,
          disabled: true,
          class: "form-control")
      %>
    </div>
    <div class="form-group col-md-6">
      <div class="sch">
      <%= label_tag("patient[email]", "Email") %>
    </div>
      <%= text_field_tag(
          "patient[email]",
          nil,
          disabled: true,
          class: "form-control")
      %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md">
      <div class="sch">
      <%= label_tag("procedure[ailment_id]", "Diagnosis") %>
    </div>
      <%= select_tag(
          "procedure[ailment_id]",
          options_for_select(
            @ailments.map(&:option_display).prepend(["Select", nil])
          ),
          class: "chosen-select form-control"
      )%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md">
      <div class="sch">
      <%= label_tag("procedure[remedy_id]", "Procedure") %>
    </div>
      <%= select_tag(
          "procedure[remedy_id]",
          options_for_select(
            @remedies.map(&:option_display).prepend(["Select", nil])
          ),
          class: "chosen-select form-control"
      )%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md">
      <div class="sch">
      <%= label_tag("procedure[physician_id]", "Physician") %>
    </div>
      <%= select_tag(
          "procedure[physician_id]",
          options_for_select(
            @physicians.map(&:option_display).prepend(["Select", nil])
          ),
          class: "chosen-select form-control"
      )%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md">
      <div class="sch">
      <%= label_tag("procedure[start_at]", "Start") %>
    </div>
      <%= datetime_field_tag("procedure[start_at]", nil, class: "form-control") %>
    </div>
  </div>
  <div class="actions">
    <%= submit_tag "Submit", class: "btn btn-primary" %>
  </div>
</div>
<% end %>
</body>

app/views/procedures/show.html.erb
<body>
	<div class="admin">
	<% if user_signed_in? %>
  	<h4 id="person">Patient: <%= @procedure.patient.first_name %> <%= @procedure.patient.last_name %></h4>
	<% end %>


<p class="doc">
  <strong>Physician: </strong> <%= @procedure.physician.first_name %> <%= @procedure.physician.last_name %> <br>

  <u><strong>Surgery Date/Time: </strong><%= @procedure.start_at.strftime("%m/%d/%Y at %I:%M%p") %></u>
</p>
</div>

<!-- *******Here starts the top half of the page******* -->

<div class="top-half">
	<div class="row-left-block">
		<div class="top-left">
			<div class="row-logo">
				<%= image_tag 'TLG', alt: "Logo", style: "width:123%" %>
			</div>
			<br>
			<div class="row-hospital">
				<b><%= @procedure.physician.hospital.name %></b><br>
				<%= @procedure.physician.hospital.address %>, <%= @procedure.physician.hospital.city %> <%= @procedure.physician.hospital.state %><br>
  						<a href= "https://goo.gl/maps/pr1GVkZiJU52">Click here for directions</a></p>
  						<br>
			</div>
		</div>

		<div class="description">
			<% if @procedure.remedy_id == 287 %>
         <b class="desc"><u><%= "Knee Ligament Repair" %></u></b><br>
         <ul class="bullets">
         <li><%= "Reattachment or reconstruction of the torn ligament by using a portion (graft) of the patellar tendon (that connects the kneecap to the tibia), the hamstring tendon (from the back of the thigh), or other autografts." %></li><br>
        <li><%= "The tendon graft may come from the person (autograft) or from an organ donor (allograft)." %></li>
       </ul>
      <% elsif @procedure.remedy_id == 23 %>
        <b class="desc"><u><%= "Rotator Cuff Repair" %></u></b><br>
        <ul class="bullets">
        <li><%= "Small rivets (called suture anchors) are often used to help attach the tendon to the bone. The suture anchors can be made of metal or material that dissolves over time, and do not need to be removed." %></li>
        <li><%= "Sutures (stitches) are attached to the anchors, which tie the tendon back to the bone." %></li>
				<li><%= "The tendons are re-attached to the bone." %></li>
      </ul>
      <% else %>
        <%= "*Please input either procedure code '23420' or '27407' on the surgical scheduling screen to see demo references to surgical descriptions." %>
      <% end %>
		</div>
	</div>


	<div class="row-right-block">
		<div class="picture-logic">
			<% if @procedure.remedy_id == 23 %>
<<<<<<< HEAD
        <%= image_tag 'rotatorcuffrepair', alt: "Rotator Cuff Repair", style: "width:100%;" %>
=======
        <%= image_tag 'rotatorcuffrepair', alt: "Rotator Cuff Repair", style: "width:120%" %>
>>>>>>> 906b761995de7bd85514b7c39028b74f21f27a63
      <% elsif @procedure.remedy_id == 287 %>
        <%= image_tag 'knee', alt: "Knee Surgery", style: "width:100%;" %>
      <% else %>
        <%= image_tag 'skeleton2', alt: "Skeletal System", style: "width:100%;" %>
      <% end %>
		</div>
	</div>
</div>

<!-- *******Top Half of Page Ends Here******* -->

<!--
*******W3School Tabs******* -->


<meta name="viewport" content="width=device-width, initial-scale=1">
<style>


</style>
</head>
<body>

<div class="clickhere">
<p><b><u>Click on the tabs below for your reminders!</u></b></p>
</div>

<div class="tab">
  <button class="tablinks" onclick="openTodo(event, 'Intro')">Patient Guide</button>
  <button class="tablinks" onclick="openTodo(event, 'Preop')">Before Surgery</button>
  <button class="tablinks" onclick="openTodo(event, 'Dayof')">Day of Surgery</button>
  <button class="tablinks" onclick="openTodo(event, 'Postop')">After Surgery</button>
</div>

<div id="Intro" class="tabcontent">
  <p>Surgery can be a very busy and stressful time!<br>
    Since you have a lot of things to remember, the tabs included here can help you to stay organized and to keep you on track in preparing for your upcoming procedure.<br>  These lists are suggestions to prepare things at home so that you can focus on a smooth recovery.</p>
</div>

<div id="Preop" class="tabcontent">
  <p>Below is a list of things that will help you to organize your time prior to surgery.<br>
    Your physician's office has given you a list of pre-operative testing to clear you for your procedure.<br>  Please take note of the timelines below.<br>  The list also includes some things to keep in mind to prepare you for recovery.
    <ul class="list">
			<%@before_tasks.each do |task| %>
  <div><li><%= task.action.activity %> : <%=task.due_at.strftime("%m/%d/%Y")%></li></div>
			<% end %>
		</ul></p>
</div>

<div id="Dayof" class="tabcontent">
 Today is the big day!  <br><br>
 Your surgery is at: </strong><%= @procedure.start_at.strftime("%m/%d/%Y at %I:%M%p") %><br>
 <b><%= @procedure.physician.hospital.name %></b><br>
        <%= @procedure.physician.hospital.address %>, <%= @procedure.physician.hospital.city %> <%= @procedure.physician.hospital.state %><br><a href= "https://goo.gl/maps/pr1GVkZiJU52">Click here for directions</a></p><br>
  	Remember a few things listed below. <br>
  	No worries, you are in good hands!
  	<ul><br/>
    <%@day_of_tasks.each do |task| %>
      <div><li><%= task.action.activity %>.</li></div>
      <% end %>
    </ul>

</div>


<div id="Postop" class="tabcontent">
  <p>Your physician has given you a list of instructions for after your surgery. <br>
    Keep in mind the points below and pay close attention your recovery. <br>
  	<ul class="list">
<%@after_tasks.each do |task| %>
  <div><li><%= task.action.activity %> <%= task.action.number %> <%= task.action.unit %> <%= task.action.timeline %> surgery.</li></div>
<% end %></p>
</ul>
</div>

<script>
function openTodo(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>
</body>